name: Setup pnpm
description: Installs Node.js and pnpm

inputs:
  node-version-file:
    description: Set a node version file to determine the Node.js version to use
    required: false
    default: .node-version

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        registry-url: 'https://registry.npmjs.org'

    - uses: pnpm/action-setup@v3
      name: Install pnpm
      id: pnpm-install
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
